# Configuration for alienhive-codex-docs setup
name: alienhive-codex-docs

# Service definitions for the big-bear-codex-docs application
services:
  CodeX Docs:
    image: ghcr.io/codex-team/codex.docs:v2.1
    container_name: CodeX Docs
    deploy:
      resources:
        reservations:
          memory: 0M
    network_mode: bridge
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: /DATA/AppData/$AppID/uploads
        target: /usr/src/app/uploads
      - type: volume
        source: /DATA/AppData/$AppID/db
        target: /usr/src/app/db
      - type: volume
        source: /DATA/AppData/$AppID/codex-docs-config.local.yaml
        target: /usr/src/app/docs-config.yaml
    environment:
      APP_CONFIG_auth_password: changeme
    x-casaos: # CasaOS specific configuration
      volumes:
        - container: /usr/src/app/uploads
          description:
            en_us: "Container Path: /usr/src/app/uploads"
        - container: /usr/src/app/db
          description:
            en_us: "Container Path: /usr/src/app/db"
        - container: /usr/src/app/docs-config.yaml
          description:
            en_us: "Container Path: /usr/src/app/docs-config.yaml"
      ports:
        - container: "3000"
          description:
            en_us: "Container Port: 3000"

# CasaOS specific configuration
x-casaos:
  architectures: # Supported CPU architectures
    - amd64
    - arm64
  main: CodeX Docs # Main service of the application
  category: AlienHiveCasaOS
  author: AlienHive-AppStore
  developer: 007darkmatter5
  icon: https://camo.githubusercontent.com/e4be3f6ff9cc8e5df4e3b8c0cceb77534f10fcbc254e5b15d86d3d36d1c468b9/68747470733a2f2f636f6465782e736f2f7075626c69632f6170702f696d672f636f6465782d6c6f676f2e737667 # Icon for the application
  
  description:
    en_us: CodeX Docs is a free docs application. It's based on Editor.js ecosystem which gives all modern opportunities for working with content. # Description in English
  tagline:
    en_us: CodeX Docs # Short description or tagline in English

  thumbnail: "" # Thumbnail image (currently empty)
  title:
    en_us: CodeX Docs
  port_map: '3000'
  scheme: http
  index: /