name: update i18n repo

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
            chmod +x ./help/action.sh
            ./help/action.sh
            cat en_us.json
            git clone https://github.com/IceWhaleTech/CasaOS-i18n.git
            ls
      
      # - name: Pushes to i18n repository
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-directory: 'output'
      #     destination-github-username: 'IceWhaleTech'
      #     destination-repository-name: 'CasaOS-i18n'
      #     user-email: a624669980@163.com
      #     target-branch: main
