name: build documentation and publish

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remove all images
        run: (find . -name "*.jpg" && find . -name "*.png") | xargs rm -f
      - name: remove file
        run: |
          rm -rf .github/workflows
          rm -rf featured-apps.json
          rm -rf category-list.json
          rm -rf .gitignore
          rm -rf README.md
          rm -rf help
      - name: show file
        run: ls
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB2 }}
        with:
          source-directory: './Apps'
          destination-github-username: 'raller1028'
          destination-repository-name: 'appstore'
          user-email: q2676515970@163.com
